
import Head from 'next/head'
import Image from 'next/image'

import { useRouter } from 'next/router';

import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Content } from '@/components/Content'


export default function Home() {
  const router = useRouter();
  const { pathname } = router;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='page'>
        <header className='header'>
          <Header />
        </header>
        <main className='main'>
          <Content pageName='Главная' />
        </main>
        <footer className='footer'>
          <Footer />
        </footer>
      </div>
    </>
  )
}
