
import Head from 'next/head'
import Image from 'next/image'
import { useContext, useState } from 'react';

import { useRouter } from 'next/router';

import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Content } from '@/components/Content'
import Profile from './profile';

import { AuthContext } from '@/context/AuthContext';


export default function Home() {

  const { isLoggedIn, setIsLoggedIn } = useContext(AuthContext)


  const router = useRouter();
  const { pathname } = router;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content pageName='Главная' isLoggedIn={isLoggedIn} setIsLoggedIn={setIsLoggedIn} />

    </>
  )
}
